# Generated by Django 6.0.4 on 2026-04-17 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='workoutset',
            options={'ordering': ['set_number']},
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='date',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('muscle gain', 'Набор массы'), ('power', 'Силовая'), ('cardio', 'Кардио / Выносливость'), ('weight_loss', 'Похудение')], default='power', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories_consumed', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('workout_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
