# Generated by Django 6.0.4 on 2026-04-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_workoutlog_options_alter_workoutset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
